export { normalizeNumber } from './quiz/normalize.ts'
export { gradeResponse } from './quiz/grade.ts'
export { WEIGHTS, observationFromCriterion, observationFromResponse } from './insight/observe.ts'
export { R0_VERSION, r0Estimate } from './insight/r0.ts'
export { rootGaps } from './insight/rootGaps.ts'
export { computeCoverage } from './authoring/coverage.ts'
export { DomainError, type ErrorCode } from './errors.ts'
export { safeReturnTo } from './identity/returnTo.ts'
export { can, authorize, type Actor, type Action, type Facts, type Decision, type Role } from './identity/policies.ts'
export { getMe } from './identity/getMe.ts'
export { switchContext } from './identity/switchContext.ts'
export { establishSession, revokeSession } from './identity/establishSession.ts'
